In [1]:
import numpy as np

In [2]:
a = np.array([23,67,6,8.76,9.8765,4])
print(a)
np.eye(3) #create the unit matrix with sdim provided by u

[23.     67.      6.      8.76    9.8765  4.    ]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
print("MAx value in arrat a ",np.max(a))
print("Min value in arrat a ",np.min(a))
print("sum of every ele of arr a ",np.sum(a))
print("mean of array a",np.mean(a))
print("median of arr a is ",np.median(a))


MAx value in arrat a  67.0
Min value in arrat a  4.0
sum of every ele of arr a  118.63650000000001
mean of array a 19.772750000000002
median of arr a is  9.318249999999999


In [4]:
print(np.sqrt(a))
print(np.square(a))
print(np.abs(a))
print(np.round(a,2))


[4.79583152 8.18535277 2.44948974 2.95972972 3.14268993 2.        ]
[ 529.         4489.           36.           76.7376       97.54525225
   16.        ]
[23.     67.      6.      8.76    9.8765  4.    ]
[23.   67.    6.    8.76  9.88  4.  ]


In [5]:
marks = np.array([34,78,90,65,78])
print(marks)
print(marks > 60)

[34 78 90 65 78]
[False  True  True  True  True]


In [6]:
marks[marks >= 50]

array([78, 90, 65, 78])

In [7]:
selected = (marks > 35) & (marks < 70)

In [8]:
selected

array([False, False, False,  True, False])

In [9]:
marks[(marks > 35) & (marks < 70)]

array([65])

In [10]:
n1 = np.array([[41,5,5],[4,74,8]])
np.sum(n1, axis=0)  #it colapse the row and give sum

array([45, 79, 13])

In [13]:
np.sum(n1,axis=1) #it collpase the col and sum it to produce thesum

array([51, 86])

In [14]:
np.sort(n1)

array([[ 5,  5, 41],
       [ 4,  8, 74]])

In [15]:
np.unique(n1)

array([ 4,  5,  8, 41, 74])

In [16]:
np.unique_counts(n1)

UniqueCountsResult(values=array([ 4,  5,  8, 41, 74]), counts=array([1, 2, 1, 1, 1]))

In [18]:
np.argmax(n1)  #it returns the index of max value

np.int64(4)

In [19]:
np.where(n1>5) #it check the each val and return the spaecific val according to that

(array([0, 1, 1]), array([0, 1, 2]))

In [20]:
np.where(n1>5, "greater","smaller")  #here we pass the value which we want to print after the condition check

array([['greater', 'smaller', 'smaller'],
       ['smaller', 'greater', 'greater']], dtype='<U7')

## Missing values

In [28]:
num = np.array([10,np.nan,20,30,40])

In [29]:
np.isnan(num) 

array([False,  True, False, False, False])

In [ ]:
np.nanmean(num)  #it find mean without the nan i.e ignore nan

np.float64(25.0)

In [33]:
np.mean(num)  #look diff between nanmean and mean 

np.float64(nan)

In [35]:
print(np.nanmax(num))
print(np.max(num))
print(np.nanmin(num))
print(np.min(num))

40.0
nan
10.0
nan


In [37]:
np.isfinite(a)

array([ True,  True,  True,  True,  True,  True])