In [1]:
import numpy as np


In [2]:
# How to check the version of numpy/
np.__version__

'2.5.3'

In [3]:
# create 1D array
a = np.array([2,5,6,7,8])
a.ndim  # checj dimension of array


1

In [4]:
# 2D array
b = np.array([[3,7],[8,9]])

In [5]:
b

array([[3, 7],
       [8, 9]])

In [6]:
b.ndim
b.shape

(2, 2)

In [7]:
# 3D array
c = np.array([[   [3,7,7],[34,6,7]],[    [4,2,4],[5,6,3]]])
c

array([[[ 3,  7,  7],
        [34,  6,  7]],

       [[ 4,  2,  4],
        [ 5,  6,  3]]])

In [8]:
c.ndim

3

In [9]:
print(c.shape) # shape of the array
print(c.size) #no. of elements
print(c.itemsize) #size of each ele in array like 8byte

(2, 2, 3)
12
8


In [10]:
print(c.nbytes) #size of ele mean 8(size of 1 ele)*12(no. of ele) = 96

96


In [11]:
#Now we create the nubered array
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
onesArr = np.ones((2,2))
onesArr

array([[1., 1.],
       [1., 1.]])

In [13]:
anyArr = np.full((3,4),7)

In [14]:
anyArr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
emptyArr = np.empty((1,6)) # it required atleast on e array

In [17]:
emptyArr

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000,
         2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [18]:
e =np.empty((1))
print(e)

[5.e-324]


In [19]:
emp =np.empty(1)
print(emp)

[5.e-324]


In [20]:
# How to print odd number using the numpy syntax: np.arange[start,stop,step] and here start =implicit and stop = explicit
print("Odd numbers between 1 to 10 are",np.arange(1,10,2))


Odd numbers between 1 to 10 are [1 3 5 7 9]


In [21]:
#Print the even no. between 1  to 50 
print("Even numbers between 1 to 50 are", np.arange(0,51,2))

Even numbers between 1 to 50 are [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


In [22]:
# one interesting method linspace
np.linspace(0,10,5) 
#OR
np.linspace(start = 0,stop=10,num=5)  
#here extracted the 5 no. randomly between 0 t0 10 but here actaul logic is 
#start-stop/num-1 i.e 10-0/5-1 10/4 =2.5 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Indexing in numpy

In [23]:
arr = np.array([3,5,6,1,7,9,3])
arr[0]

np.int64(3)

In [24]:
arr = np.array([[3,5,6],[7,9,3]])
print(arr[1,1])

9


In [25]:
arr[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

## Slicing in numpy

In [27]:
arr = np.array([3,5,6,1,7,9,3])
print("The slice of arr from 0 to 3: ", arr[:4])

The slice of arr from 0 to 3:  [3 5 6 1]


In [28]:
arr[::]

array([3, 5, 6, 1, 7, 9, 3])

In [29]:
arr[-4:]

array([1, 7, 9, 3])

In [30]:
arr[2:6]  # In slicing starting ind is implicit and end ind is explicit

array([6, 1, 7, 9])

In [31]:
arr1 = np.array([[3,5,6],[7,9,3]])

In [32]:
arr1[0:1]

array([[3, 5, 6]])

In [33]:
arr1[0:2]

array([[3, 5, 6],
       [7, 9, 3]])

In [34]:
arr1[1: , 0:2]

array([[7, 9]])

In [45]:
farr = arr1.flatten()  #ruturn the flatten arr  It is used when we have a ndim array and now want that in 1D
print(farr)




[3 5 6 7 9 3]


In [46]:
rarr = arr1.ravel()
print(rarr)
arr1.ndim
print()

[3 5 6 7 9 3]



In [47]:
arr1.T  # it transpose the matrix

array([[3, 7],
       [5, 9],
       [6, 3]])

In [50]:
arr1.reshape(3,2)  # keep in mind that at  a time of  reshaping the array is that we reshape only in dimension whose multplication ie eqal to 
# the size of array

array([[3, 5],
       [6, 7],
       [9, 3]])

In [52]:
arr1.reshape(1,6)

array([[3, 5, 6, 7, 9, 3]])

## Operations

In [53]:
a

array([2, 5, 6, 7, 8])

In [54]:
b

array([[3, 7],
       [8, 9]])

In [55]:
n1 = np.array([2,4,5,6,9])
n2=np.array([23,56,1,8,9]) 
#To perform the operations on array we need arrays with same size

In [56]:
n1+n1

array([ 4,  8, 10, 12, 18])

In [57]:
n1*n2

array([ 46, 224,   5,  48,  81])

In [58]:
n1/n2

array([0.08695652, 0.07142857, 5.        , 0.75      , 1.        ])

In [59]:
n1+n2

array([25, 60,  6, 14, 18])

In [60]:
print(n1)
print(n2)
n1%n2

[2 4 5 6 9]
[23 56  1  8  9]


array([2, 4, 0, 6, 0])

In [61]:
print(n1)
print(n2)
n2%n1

[2 4 5 6 9]
[23 56  1  8  9]


array([1, 0, 1, 2, 0])

In [62]:
print(n1)
print(n2)
n1**3

[2 4 5 6 9]
[23 56  1  8  9]


array([  8,  64, 125, 216, 729])

In [63]:
print(n1)
print(n2)
n2//n1

[2 4 5 6 9]
[23 56  1  8  9]


array([11, 14,  0,  1,  1])

In [65]:
n = np.array([[2,4,5],[4,6,9]])
m=np.array([23,56,1,])